version: '3.8'

services:
  app:
    build: .
    container_name: nlp_service
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/onnx_models/phishing_detection.onnx
      - TOKENIZER_PATH=distilbert-base-uncased
      - KAFKA_BROKER=kafka:9092
      - INPUT_TOPIC=threat-detection-input
      - OUTPUT_TOPIC=threat-detection-output
    depends_on:
      - kafka

  kafka:
    image: wurstmeister/kafka
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_service
    ports:
      - "2181:2181"
